- src/hashbrown.cr
- src/modules/functions/generate_hash.cr
- src/modules/ui/hash_list.ui
- src/modules/ui/style.css
- src/modules/views/main.cr
(CSS gets loaded using macros)
closes: #30
> Use row subtitles to display the hashes

- Makefile
- README.md
- extra/dev.geopjr.Hashbrown.json
- shard.yml
- spec/copy_spec.cr
- src/hashbrown.cr
- src/modules/functions/file_set.cr
- src/modules/functions/generate_hash.cr
- src/modules/global_vars.cr
- src/modules/ui/hash_list.ui
- src/modules/ui/header_left.ui
- src/modules/ui/header_right.ui
- src/modules/ui/spinner.ui
- src/modules/ui/tools.ui
- src/modules/ui/welcomer.ui
- src/modules/views/tools/compare.cr
This PR replaces the use of channels with fibers.
Spawning each calculation in individual fibers seems to get at least one blocked in the main one, so we just spawn one for now. Additionally an extra flag is needed at compile time to enable concurrency, `-Dpreview_mt`.
closes: #37
> feat: channels -> fibers

- src/modules/functions/file_set.cr
Not sure if there's a better/more reliable (or even faster) way to check, but for now checks if the path parents include `run` & `user` (only for flatpak, check is being done with macros)
closes: #57
> feat: don't show StatusPage description when portal is used

- src/modules/views/main.cr
> feat: feedback on copy

- Makefile
- data/dev.geopjr.Collision.gschema.xml
- data/dev.geopjr.Collision.json
- src/collision.cr
- src/collision/functions/settings.cr
- src/collision/views/main.cr
for window settings (width, height, maximized)
If you depend on the `Makefile` you probably have nothing more to do.
If not, you now have to install a gschema and compile them (see Makefile).
If for some reason you don't want to deal with it, you can just pass `-Ddisable_gschema` during compile-time (Collision will work as expected, it just won't have any of the functions that depend on it (remembering window size and whether it is maximized))
On dev/debug mode gschema is disabled by default. You can force enable it by passing `-Denable_gschema` during compile-time, however you are also going to need to install the gschema (the errors will let you know).
Nothing to do, gschema is enabled & installed.
> feat: gschema

- src/collision.cr
- src/collision/functions/file.cr
- src/collision/views/main.cr
- src/collision/views/tools/compare.cr
- src/collision/views/welcomer.cr
This PR allows Collision to open files either from CLI:
```
$ collision ./my/file.txt
```
or through your file manager's "Open With..." context menu entry:
[Recording of a GNOME desktop with the Files app open. There's a file named test.txt. User right clicks it and selects the open with context entry. Afterwards, a popup to select the app to open it with shows up. User selects Collision. Then the Collision up shows up with that file's hashes.](https://user-images.githubusercontent.com/18014039/199318847-7abcab58-d9be-4735-bf2c-8bb50cec8d5d.webm)
Some changes to the way file setting works had to be upstreamed from the DnD PR (#115), which included some additional error handling and bug fixes.
As suggested partially in: #53
> Handle open signal

- src/collision/views/main.cr
Collision should handle open signal even after welcomer
f1xes: https://github.com/GeopJr/Collision/issues/104#issuecomment-1322576823
> fix: open signal while already open

- data/dev.geopjr.Collision.gresource.xml
- data/ui/shortcuts_window.ui
- po/POTFILES
- src/collision.cr
- src/collision/views/main.cr
application: Use default GTK help-overlay
- GTK can handle help-overlay with some specifications.
data: Add shortcuts_window.ui to potfiles
- It was missing in POTFILES.
> Update help overlay

- nautilus-extension/collision-extension.py
`subprocess.CalledProcessError` can't be invoked if you don't import `subprocess` entirely! :yum:
> Fixed an import error on the nautilus extension

- src/collision/functions/headbar.cr
I couldn't test this (The project somehow doesn't build for me in Builder), but it _should_ work.
> HeaderBar: Set centering_policy to strict

- data/dev.geopjr.Collision.metainfo.xml.in
The descriptions under the Release tag don't necessarily need to be marked as translatable. However, this is the description of the application and can be seen in GNOME Software. So, leave it translatable.
> data: Fix app description marked as untranslated

- data/dev.geopjr.Collision.metainfo.xml.in
These URL is visible on Flathub and GNOME Control Center.
More information: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url
> appdata: add vcs-browser support

- data/dev.geopjr.Collision.metainfo.xml.in
This metadata is invalid: custom data is a dictionary and using the same key multiple times in a dictionary does not work
More information: https://github.com/ximion/appstream/issues/476
> appdata: Remove Purism metadata

- data/dev.geopjr.Collision.metainfo.xml.in
This tag is optional but in use most of GNOME apps.
"This optional tag indicates possible methods to launch the software described in this component"
More information: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable
> appdata: Add missing the `launchable` tag

- data/dev.geopjr.Collision.desktop.in
- data/dev.geopjr.Collision.gresource.xml
- data/dev.geopjr.Collision.json
- data/dev.geopjr.Collision.metainfo.xml.in
- data/ui/application.ui
- data/ui/hash_row.ui
- po/POTFILES
- po/dev.geopjr.Collision.pot
- shard.lock
- shard.yml
- spec/compare_spec.cr
- spec/hash_generator_spec.cr
- spec/spec_helper.cr
- src/collision.cr
- src/collision/functions/checksum.cr
- src/collision/widgets/hash_row.cr
- src/collision/window.cr
fix: #102 
fix: #176 
- Adds Blake3 (shard), CRC32 (std), Adler32 (std)
- Dynamically creates the rows
- Use symbols for the hash types
- Use named tuple for the functions (type: digest)
- Move away from openssl and instead use digest directly
- Create new digest instances for every calculation (fixes crash due to finalizing > 1)
- Support for opening multiple files from the file picker (opens new windows)
- Shows loading screen when opening with file
TODO:
- #166
- ~~Update flatpak config~~
> feat: Blake3, CRC32, Adler32, progress bar, cleanup

- data/dev.geopjr.Collision.metainfo.xml.in
- Add the `<developer><name>` tag
- Mark the `<developer_name>` tag as deprecated
> feat(appdata): Improve appdata for AppStream 1.0

- .github/workflows/ci.yml
- Makefile
- data/dev.geopjr.Collision.json
- spec/hash_generator_spec.cr
> feat(ci): validate appstream

- data/dev.geopjr.Collision.json
- shard.lock
- shard.yml
- spec/hash_generator_spec.cr
The previous version of blak3cr would depend on a postinstall script + makefile to build blake3c. It now uses a macro to detect the correct arch and run the correct commands to properly build it.
> chore: bump blake3.cr

- data/dev.geopjr.Collision.metainfo.xml.in
Appstream decided to use reverse DNS for developer IDs.
More information: https://github.com/ximion/appstream/issues/575
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer
> Update Developer ID

- spec/hash_generator_spec.cr
Sometimes specs would fail at random due to 'missing key' even though it shouldn't be. That was due to accessing a hash outside the thread.
Initializing all keys with an empty string *outside* mt, seems to prevent it
> fix(spec): multithreading array access fail

- src/collision/functions/feedback.cr
- src/collision/window.cr
Some widgets were missing tooltip texts, some had to change, some had wrong ones
> fix(a11y): add labels when possible

- data/dev.geopjr.Collision.metainfo.xml.in
It appears that the appstream project no longer supports
`translatable=no` properties, and gettext extract the
`translatable=no` marked strings as translatable.
I opened an issue to inform about the situation, but `translatable=no`
properties are not accepted by developers. You can find the issue
here: https://github.com/ximion/appstream/issues/623
**Please test your script or string extraction process
before merging this PR.**
> In MetaInfo files, each individual paragraph of a description
> (or enumerated entry) is translated individually, however,
> you can only exclude the complete block from being translated
> by adding `translate="no"` to the description element.
Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html
welcome.gnome.org is …
> appdata: `translate=no` properties

- data/ui/application.ui
- shard.lock
- src/collision/window.cr
Newer gi-crystal versions made it super easy to work with async methods, thanks Hugo!
Filechoosernative has been deprecated for a while and finally I was able to move to FileDialog
> feat: FileChooserNative => FileDialog
